# Generated by Django 4.1.3 on 2022-12-01 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.bookstore'),
            preserve_default=False,
        ),
    ]
