# Generated by Django 4.1.3 on 2022-12-01 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userbook_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbook',
            old_name='book',
            new_name='store',
        ),
    ]
