# Generated by Django 4.1.3 on 2022-12-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_book_userbook_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='publish_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
